version: "3.8"
services:
  ## database
  mysql-database-container:
    container_name: mysql-database-container
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=e-commerce
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - e-commerce-database:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    
  ## server
  server:
    depends_on:
      - mysql-database-container
    container_name: expressjs-server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/server
    ports:
      - 9999:9999
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - SERVER_HOST=localhost
      - SERVER_PORT=9999
      - JWT_SECRET=JWT_SECRETS
    
      - DATABASE_HOST=mysql-database-container
      - DATABASE_NAME=e-commerce
      - DATABASE_PORT=3306
      - DIALECT=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
    stdin_open: true
    tty: true

networks:
  frontend: 
    name: client-network
  backend:
    name: server-network
  

volumes:
  e-commerce-database:
