version: "3.8"
services:
  ## client


  ## server
  server:
    container_name: expressjs-server-container
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /e-commerce/server
    volumes:
      - ./:/e-commerce/server
    ports:
      - 9999:8000
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - SERVER_HOST=localhost
      - SERVER_PORT=9999
      - JWT_SECRET=JWT_SECRETS

      - DATABASE_HOST=server-network-alias
      - DATABASE_NAME=e-commerce
      - DATABASE_PORT=3307
      - DIALECT=mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
  
  ## database
  mysql:
    container_name: mysql-database-container
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=e-commerce
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - e-commerce-database:/var/lib/mysql
    ports:
      - 3307:3306
    # expose:
    #   - 3306
networks:
  backend:
    name: app-network
  

volumes:
  e-commerce-database:
